### GET request to example server
GET {{host}}/api/image
Content-Type: */*

###

GET {{host}}/api/image/2
Content-Type: */*

###
### Not implemented rn
GET {{host}}/api/image/person/1
Content-Type: */*

###

POST {{host}}/api/image
Content-Type: application/json

{
  "description": "Profile picture of Maria Bauer",
  "person": {
    "dob": "1985-03-15",
    "firstName": "Anna",
    "gender": true,
    "isWorker": true,
    "lastName": "Müller",
    "roomNo": "101"
  },
  "base64Image": "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8z8BQDwAF/wKdc3UAAAAASUVORK5CYII="

}

###

###

DELETE {{host}}/api/image/2
Content-Type: application/json