GET {{host}}/api/tagalongstories
Content-Type: application/json

###
POST {{host}}/api/tagalongstories
Content-Type: application/json

{
  "name": "Geschichten aus Wien",
  "icon": "SGVsbHA=",
  "gameType": {
    "id": "TAG_ALONG_STORY",
    "name": "Mitmachgeschichten"
  },
  "enabled": true
}

###
PUT {{host}}/api/tagalongstories/2
Content-Type: application/json

{
  "name": "Geschichten aus Linz",
  "icon": "SGVsbHA=",
  "gameType": {
    "id": "TAG_ALONG_STORY",
    "name": "Mitmachgeschichten"
  },
  "enabled": false
}
###
DELETE {{host}}/api/tagalongstories/2
###

GET {{host}}/api/tagalongstories/2/steps
Content-Type: application/json
###

POST {{host}}/api/tagalongstories/2/steps
Content-Type: application/json

{
  "game": {
    "name": "Geschichten aus der Voralberg",
    "icon": null,
    "gameType": {
      "id": "TAG_ALONG_STORY",
      "name": "Mitmachgeschichten"
    },
    "enabled": true
  },
  "index": 1,
  "image": {
    "person": null,
    "image": "SGVsbHA=",
    "url": "Cloud URL",
    "description": "Vorarlberg"
  },
  "move": {
    "id": 1,
    "name": "emote_hurra",
    "description": "Hurra"
  },
  "text": "GAME ID 5"
}

###
DELETE {{host}}/api/tagalongstories/2/steps/5
Content-Type: application/json
