GET {{host}}/api/tagalongstories
Content-Type: application/json

###
POST {{host}}/api/tagalongstories
Content-Type: application/json

{
  "name": "Geschichten vom Hallstätter See",
  "icon": null,
  "gameType": {
    "id": "TAG_ALONG_STORY",
    "name": "Mitmachgeschichten"
  },
  "enabled": true
}