apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/mealplan

images:
  - name: ghcr.io/2425-4chif-syp/01-projekte-2025-4chif-syp-pepper-minigames/mealplan-backend
    newTag: latest
  - name: ghcr.io/2425-4chif-syp/01-projekte-2025-4chif-syp-pepper-minigames/mealplan-frontend-leocloud
    newTag: latest

patches:
  - path: patch-ingress.yaml
  - path: patch-image-pull-secret.yaml
  - path: patch-postgres-resources.yaml
  - path: patch-backend-resources.yaml
  - path: patch-frontend-resources.yaml
