apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealplan-backend
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealplan-frontend
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
