apiVersion: v1
kind: ConfigMap
metadata:
  name: mealplan-backend-config
  labels:
    app.kubernetes.io/name: mealplan-backend
    app.kubernetes.io/part-of: pep-mealplan
data:
  QUARKUS_HTTP_HOST: 0.0.0.0
  QUARKUS_DATASOURCE_DB_KIND: postgresql
  QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://mealplan-postgres:5432/mealplan
  QUARKUS_HIBERNATE_ORM_SCHEMA_MANAGEMENT_STRATEGY: update
  QUARKUS_HTTP_PROXY_PROXY_ADDRESS_FORWARDING: "true"
