apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealplan-postgres-data
  labels:
    app.kubernetes.io/name: mealplan-postgres
    app.kubernetes.io/part-of: pep-mealplan
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
