services:
  backend:
    container_name: backend
    image: ghcr.io/2425-4chif-syp/01-projekte-2025-4chif-syp-pepper-minigames/pepper-backend:latest
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: curl -f http://localhost:8080/q/health
      start_period: 30s
      start_interval: 2s
      retries: 10
    ports:
      - 8080:8080
    environment:
      - quarkus.datasource.jdbc.url=jdbc:postgresql://postgres:5432/db
    env_file:
      - ../backend_v2/.env
    networks:
      - pepper_net
