services:
  backend:
    container_name: backend
    build:
      context: ../backend_v2
      dockerfile: ../backend_v2/src/main/docker/Dockerfile
    env_file:
      - ../backend_v2/.env
    environment:
      - QUARKUS_PROFILE=prod
    networks:
      - peppernet
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    container_name: frontend
    build:
      context: ../frontend
      dockerfile: ../frontend/docker/Dockerfile
    depends_on:
      - backend
    networks:
      - peppernet
    ports:
      - "80:80"
    restart: unless-stopped

  db:
    container_name: postgres
    image: postgres:17.0-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: db
    ports:
      - 5432:5432
    volumes:
      - ./db-postgres/db:/var/lib/postgresql/data
      - ./db-postgres/import:/import
    networks:
      - peppernet

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:8.12
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./db-postgres/pgadmin:/root/.pgadmin
    ports:
      - 8090:80
    networks:
      - peppernet
    restart: unless-stopped

networks:
  peppernet:
    driver: bridge
