services:
  nginx:
    container_name: www
    image: ghcr.io/2425-4chif-syp/01-projekte-2025-4chif-syp-pepper-minigames/pepper-frontend:latest
    ports:
      - 4200:80
    healthcheck:
      test: curl --fail --head -fsS http://localhost || exit 1
      interval: 40s
      timeout: 30s
      retries: 2
      start_period: 10s
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - pepper_net
