# docker compose file for our standalone postgres database
services:
  postgres:
    container_name: postgres
    image: postgres:17-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - setup:/docker-entrypoint-initdb.d
#      - ./postgres/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql volume mounts don't work on windoze
    environment:
      - POSTGRES_PASSWORD=app
      - POSTGRES_USER=app
      - POSTGRES_DB=db
    healthcheck:
          test: pg_isready --dbname=db --username=app
          interval: 60s
          timeout: 10s
          retries: 3
          start_period: 30s
          start_interval: 2s

volumes:
  postgres:
  setup:
