# docker compose file for our standalone postgres database
services:
  postgres:
    container_name: postgres
    image: postgres:17-alpine
    ports:
      - 5432:5432
    volumes:
      - ./db-postgres/db:/var/lib/postgresql/data
      - ./db-postgres/import:/import
    #      - postgres:/var/lib/postgresql/data
    #      - setup:/docker-entrypoint-initdb.d
    #      - ./postgres/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql volume mounts don't work on windows
    environment:
      - POSTGRES_PASSWORD=app
      - POSTGRES_USER=app
      - POSTGRES_DB=db
    healthcheck:
      test: pg_isready --dbname=db --username=app
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
      start_interval: 2s

volumes:
  postgres:
  setup:

networks:
  custom_net:
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24