# Node.js Basis-Image
FROM node:18-alpine

# Setze das Arbeitsverzeichnis
WORKDIR /app

COPY MenuAssistent_Website/package.json package.json
COPY MenuAssistent_Website/package-lock.json package-lock.json
RUN ls -l /app && cat /app/package.json | grep build
RUN npm ci --prefer-offline

# Kopiere den gesamten Frontend-Code
COPY MenuAssistent_Website/ .

# Baue das Frontend
RUN npm run build

# Standard-Startbefehl
CMD ["sh", "-c", "npm run build"]