name: Build and Deploy Pepper-Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build-and-deploy-frontend:
    permissions: write-all
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Find and set image tag
        run: |
          if test "${{ github.ref_name }}" = "main"; then tag="latest"; else tag="dev"; fi
          echo "IMAGE_TAG=${tag}" >> "$GITHUB_ENV"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Build frontend
        run: ./frontend/build.sh

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./frontend/docker/Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}/pepper-frontend:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to VM
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ghcr.io/${{ github.repository }}/pepper-frontend:${{ env.IMAGE_TAG }}
            docker stop www || true
            docker rm www || true
            docker run -d --name www -p 4200:80 ghcr.io/${{ github.repository }}/pepper-frontend:${{ env.IMAGE_TAG }}
