name: Build docker images
on:
  push:
    paths:
      - 'Backend_V2/**'
      - 'cicd/**'
    branches:
      - main
      - develop
  workflow_dispatch:
jobs:
  build-server-image:
    permissions: write-all
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Find and set image tag
        run: |
          if test "${{ github.ref_name }}" = "main"; then tag="latest"; else tag="dev"; fi
          echo "IMAGE_TAG=${tag}" >> "$GITHUB_ENV"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./Backend_V2
          file: ./Backend_V2/src/main/docker/Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}/pepper-backend:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

