name: CI/CD Pipeline for Quarkus Docker Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'backend_v2/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend_v2

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

      - name: Deploy to VM (SSH)
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          run: |
            if [ $(docker ps -q -f name=backend) ]; then
              docker stop backend
              docker rm backend
            fi
            
            docker pull ${{ secrets.DOCKER_USERNAME }}/backend:latest

            docker run -d \
              -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
              -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
              -e CHATGBT_API_KEY=${{ secrets.CHATGBT_API_KEY }} \
              --network pepperdb_postgres \
              --name backend \
              -p 8080:8080 \
              --restart unless-stopped \
              ${{ secrets.DOCKER_USERNAME }}/backend:latest
