name: PEPPER Backend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'Backend_V2/**'
      - '.github/workflows/**'
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: 'Backend_V2/pom.xml' # optional
      - name: Build with Maven
        run: |
          cd Backend_V2
          mvn verify -B -DskipTests -Dquarkus.package.type=uber-jar
      - name: install ssh key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_SERVER_PRIVATE_KEY }}
      - name: create .ssh/known_hosts
        run: |
          ssh-keyscan -H -t ed25519 -v ${{ secrets.SERVER_IP }}  >> ~/.ssh/known_hosts
      - name: copy binaries to vm
        run: |
          ls -l Backend_V2/target/
          ls ~/.ssh
          scp Backend_V2/target/pepper-dm-1.0.0-SNAPSHOT-runner.jar ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}: