name: Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci
        working-directory: frontend/angular-demo


      - name: Build Angular project
        run: npm run build -- --configuration=production
        working-directory: frontend/angular-demo

      - name: Zip build directory
        run: |
          tar -zcvf ../../../../../dist.tar.gz ./
        working-directory: frontend/angular-demo/dist/angular-demo/browser

      - name: Copy zip to server via SCP
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: dist.tar.gz
          target: /tmp/
          strip_components: 0

      - name: Unzip on server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html/
            rm -rf *
            tar -xzf /tmp/dist.tar.gz
            tar -tf /tmp/dist.tar.gz
            rm /tmp/dist.tar.gz