name: Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci
        working-directory: frontend/

      - name: Build Angular project
        run: npm run build -- --configuration=production
        working-directory: frontend/

      - name: Create deployment archive
        run: tar --warning=no-file-changed -zcvf dist.tar.gz ./
        working-directory: frontend/dist/pepper-angular

      - name: Upload archive via SCP
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: frontend/dist/pepper-angular/dist.tar.gz
          target: /tmp/

      - name: Deploy on server via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "📦 Inhalt der .tar.gz prüfen..."
            tar -tf /tmp/dist.tar.gz
            echo "📁 Vorherige Dateien löschen..."
            rm -rf /var/www/html/*
            echo "📂 Entpacken..."
            tar -xzf /tmp/dist.tar.gz -C /var/www/html/
            echo "🧹 Aufräumen..."
            rm /tmp/dist.tar.gz
